[build]
  command   = "npm run build"
  environment = { NODE_VERSION = "18.2.0" }

# [[plugins]]
#   package = "netlify-plugin-cache-folder"

[[headers]]
  for = "/*"
    [headers.values]
  #   Content-Security-Policy = "default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; object-src 'none'; script-src 'self'; style-src 'self'; font-src 'self'"
  #   Content-Security-Policy = "default-src https://*.dgrammatiko.dev; script-src https://*.dgrammatiko.dev 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: https://*.dgrammatiko.dev; font-src https://*.dgrammatiko.dev;"
  #   Permissions-Policy = "camera=(); display-capture=(); document-domain=(); geolocation=(); microphone=(); payment=(); usb=();"
      Referrer-Policy = "same-origin"
      Strict-Transport-Security = "max-age=15768000"
      X-Content-Type-Options = "nosniff"
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"

      Link = '''</static/fonts/dgrammatiko.woff2>; rel=preload; as=font; crossorigin'''

[[headers]]
  for = "/*.webmanifest"
    [headers.values]
      Content-Type = "application/manifest+json"

[[headers]]
  for = "/static/*"
    [headers.values]
      Cache-Control = "public, max-age=31536000"
