build:
  command: npm run build
  environment:
    NODE_VERSION: 18.2.0
    NODE_ENV: production
    DEBUG: false
  processing:
    skip_processing: true
    css:
      bundle: false
      minify: false
    js:
      bundle: false
      minify: false
    html:
      pretty_urls: false
    images:
      compress: false

headers:
  - for: /*
    values:
      Referrer-Policy: same-origin
      Strict-Transport-Security: max-age=15768000
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: 1; mode=block
  #   Content-Security-Policy: default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; img-src 'self'; media-src 'self'; object-src 'none'; script-src 'self'; style-src 'self'; font-src 'self'
  #   Content-Security-Policy: default-src https://*.dgrammatiko.dev; script-src https://*.dgrammatiko.dev 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: https://*.dgrammatiko.dev; font-src https://*.dgrammatiko.dev;
  #   Permissions-Policy: camera=(); display-capture=(); document-domain=(); geolocation=(); microphone=(); payment=(); usb=();
      Link: |2-
            <assets/fonts/Qw3PZQNVED7rKGKxtqIqX5E-AVSJrOCfjY46_LjQbMZhKSbpUVzEEQ.woff>; rel=preload; as=font, \
            <assets/fonts/dgrammatiko.woff2>; rel=preload; as=font

  - for: /*.webmanifest
    values:
      Content-Type: application/manifest+json

  - for: /static/*
    values:
      Cache-Control: public, max-age=31536000

